# Generated by Django 4.2.16 on 2024-11-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=20)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('fin_co_no', models.CharField(max_length=20)),
                ('join_way', models.CharField(max_length=20)),
                ('spcl_cnd', models.TextField()),
                ('join_member', models.TextField()),
                ('kor_co_nm', models.CharField(max_length=20)),
                ('intr_rate', models.FloatField(max_length=20)),
                ('intr_rate2', models.FloatField(max_length=20)),
                ('intr_rate_type_nm', models.CharField(max_length=20)),
                ('rsrv_type_nm', models.CharField(max_length=20)),
                ('save_trm', models.IntegerField()),
            ],
            options={
                'unique_together': {('fin_prdt_cd', 'fin_co_no', 'fin_prdt_nm')},
            },
        ),
    ]
