# Generated by Django 4.2.16 on 2024-11-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_depositproducts_rsrv_type_nm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='depositproducts',
            unique_together={('fin_prdt_cd', 'fin_co_no', 'fin_prdt_nm', 'save_trm')},
        ),
        migrations.AlterUniqueTogether(
            name='savingproducts',
            unique_together={('fin_prdt_cd', 'fin_co_no', 'fin_prdt_nm', 'save_trm')},
        ),
    ]
