# Generated by Django 4.2.16 on 2024-11-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_depositproducts_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='max_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='savingproducts',
            name='max_limit',
            field=models.IntegerField(null=True),
        ),
    ]
