# Generated by Django 4.2.16 on 2024-11-21 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavingProducts',
        ),
    ]
